<?php

acf_add_local_field_group([
    'key' => 'group_only_page_fields',
    'title' => 'Additional fields',
    'fields' => [
        // fields

        // banner
        [
            'key' => 'f_only_tab_banner',
            'label' => 'Banner',
            'name' => '',
            'type' => 'tab',
            'placement' => 'top',
        ],
        [
            'key' => 'f_p_only_bg',
            'label' => 'Background image ',
            'name' => 'f_p_only_bg',
            'type' => 'image',
        ],
        [
            'key' => 'f_p_only_title',
            'label' => 'Title h1',
            'name' => 'f_p_only_title',
            'type' => 'text',
        ],
        [
            'key' => 'f_p_only_sub_title',
            'label' => 'Title right',
            'name' => 'f_p_only_sub_title',
            'type' => 'text',
        ],
        [
            'key' => 'f_p_only_p',
            'label' => 'Description right',
            'name' => 'f_p_only_p',
            'type' => 'text',
        ],
        // end banner

        // what
        [
            'key' => 'f_only_tab_what',
            'label' => 'What',
            'name' => '',
            'type' => 'tab',
            'placement' => 'top',
        ],
        [
            'key' => 'f_only_what_title',
            'label' => 'Title',
            'name' => 'f_only_what_title',
            'type' => 'text',
        ],
        [
            'key' => 'f_only_what_description',
            'label' => 'Description',
            'name' => 'f_only_what_description',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'toolbar' => 'full',
            'media_upload' => 0,
            'default_value' => '',
            'tabs' => 'all',
            'max_width' => '',
            'min_width' => '',
            'max_height' => '',
            'min_height' => '',
        ],
        [
            'key' => 'f_only_what_file',
            'label' => 'PDF',
            'name' => 'f_only_what_file',
            'type' => 'file',
            'instructions' => '',
            'required' => 0,
            'return_format' => 'url',
            'library' => 'all',
            'mime_types' => 'pdf',
        ],
        [
            'key' => 'f_only_what_img',
            'label' => 'Picture',
            'name' => 'f_only_what_img',
            'type' => 'image',
        ],
        [
            'key' => 'f_only_what_repeater',
            'label' => 'Repeater',
            'name' => 'f_only_what_repeater_fields',
            'type' => 'repeater',
            'instructions' => 'Add multiple entries with three text fields',
            'required' => 0,
            'collapsed' => '',
            'min' => 1,
            'button_label' => 'Add new entry',
            'sub_fields' => [
                [
                    'key' => 'f_only_what_repeater_name',
                    'label' => 'Name',
                    'name' => 'name',
                    'type' => 'text',
                    'required' => 1,
                    'wrapper' => [
                        'width' => '50%',
                    ],
                ],
                [
                    'key' => 'f_only_what_repeater_description',
                    'label' => 'Description',
                    'name' => 'description',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'toolbar' => 'full',
                    'media_upload' => 0,
                    'default_value' => '',
                    'tabs' => 'all',
                    'max_width' => '',
                    'min_width' => '',
                    'max_height' => '',
                    'min_height' => '',
                    'wrapper' => [
                        'width' => '50%',
                    ],
                ],
            ],
        ],
        // end

        // resources
        [
            'key' => 'f_only_tab_resources',
            'label' => "Resources",
            'name' => '',
            'type' => 'tab',
            'placement' => 'top',
        ],
        [
            'key' => 'f_only_resources_title',
            'label' => 'Title',
            'name' => 'f_only_resources_title',
            'type' => 'text',
        ],
        [
            'key' => 'f_only_resources_repeater',
            'label' => 'Repeater',
            'name' => 'f_only_resources_repeater',
            'type' => 'repeater',
            'instructions' => 'Add multiple entries with three text fields',
            'required' => 0,
            'collapsed' => '',
            'min' => 1,
            'button_label' => 'Add new entry',
            'sub_fields' => [
                [
                    'key' => 'f_only_resources_repeater_description',
                    'label' => 'Description',
                    'name' => 'description',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'toolbar' => 'full',
                    'media_upload' => 0,
                    'default_value' => '',
                    'tabs' => 'all',
                    'max_width' => '',
                    'min_width' => '',
                    'max_height' => '',
                    'min_height' => '',
                    'wrapper' => [
                        'width' => '50%',
                    ],
                ],
                [
                    'key' => 'f_only_resources_repeater__img',
                    'label' => 'Picture',
                    'name' => 'img',
                    'type' => 'image',
                ],
            ],
        ],
        // end resources

        // innovation
        [
            'key' => 'f_only_tab_innovation',
            'label' => "Innovation",
            'name' => '',
            'type' => 'tab',
            'placement' => 'top',
        ],
        [
            'key' => 'f_only_innovation_title',
            'label' => 'Title',
            'name' => 'f_only_innovation_title',
            'type' => 'text',
        ],
        [
            'key' => 'f_only_innovation_repeater',
            'label' => 'Repeater',
            'name' => 'f_only_innovation_repeat_fields',
            'type' => 'repeater',
            'instructions' => 'Add multiple entries with three text fields',
            'required' => 0,
            'collapsed' => '',
            'min' => 1,
            'layout' => 'row',
            'button_label' => 'Add new entry',
            'sub_fields' => [
                [
                    'key' => 'innovation_repeater_image',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                ],
                [
                    'key' => 'innovation_repeater_name',
                    'label' => 'Name',
                    'name' => 'name',
                    'type' => 'text',
                    'required' => 1,
                ],
                [
                    'key' => 'innovation_repeater_description',
                    'label' => 'Description',
                    'name' => 'description',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'toolbar' => 'full',
                    'media_upload' => 0,
                    'default_value' => '',
                    'tabs' => 'all',
                    'max_width' => '',
                    'min_width' => '',
                    'max_height' => '',
                    'min_height' => '',
                ],

            ],
        ],
        // end innovation

        // Execution
        [
            'key' => 'f_only_tab_exection',
            'label' => "Execution",
            'name' => '',
            'type' => 'tab',
            'placement' => 'top',
        ],
        [
            'key' => 'f_only_exection_title',
            'label' => 'Title',
            'name' => 'f_only_exection_title',
            'type' => 'text',
        ],
        [
            'key' => 'f_only_exection_repeater',
            'label' => 'Repeater',
            'name' => 'f_only_exection_repeat_fields',
            'type' => 'repeater',
            'instructions' => 'Add multiple entries with three text fields',
            'required' => 0,
            'collapsed' => '',
            'min' => 1,
            'layout' => 'row',
            'button_label' => 'Add new entry',
            'sub_fields' => [
                [
                    'key' => 'exection_repeater_image',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                ],
                [
                    'key' => 'exection_repeater_name',
                    'label' => 'Name',
                    'name' => 'name',
                    'type' => 'text',
                    'required' => 1,
                ],
                [
                    'key' => 'exection_repeater_description',
                    'label' => 'Description',
                    'name' => 'description',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'toolbar' => 'full',
                    'media_upload' => 0,
                    'default_value' => '',
                    'tabs' => 'all',
                    'max_width' => '',
                    'min_width' => '',
                    'max_height' => '',
                    'min_height' => '',
                ],
            ],
        ],
        // Social
        [
            'key' => 'f_ser_tab_only_socail',
            'label' => 'Social',
            'name' => '',
            'type' => 'tab',
            'placement' => 'top',
        ],
        [
            'key' => 'f_ser_only_socail_title',
            'label' => 'Title',
            'name' => 'f_ser_only_socail_title',
            'type' => 'text',
        ],

        [
            'key' => 'f_only_socail_repeater',
            'label' => 'Repeater',
            'name' => 'f_only_socail_repeat_fields',
            'type' => 'repeater',
            'instructions' => 'Add multiple entries with three text fields',
            'required' => 0,
            'collapsed' => '',
            'min' => 1,
            'layout' => 'row',
            'button_label' => 'Add new entry',
            'sub_fields' => [
                [
                    'key' => 'repea_only_socail_icon_soc',
                    'label' => 'Image',
                    'name' => 'icon',
                    'type' => 'image',
                ],
                [
                    'key' => 'repea_only_socail_name',
                    'label' => '%',
                    'name' => 'percend',
                    'type' => 'text',
                    'required' => 1,
                ],
                [
                    'key' => 'repea_only_socail_p',
                    'label' => 'Info',
                    'name' => 'info',
                    'type' => 'text',
                ],
                [
                    'key' => 'repea_only_socail_quantity',
                    'label' => 'Quantity',
                    'name' => 'quantity',
                    'type' => 'text',
                ],
                [
                    'key' => 'repea_only_socail_Impressions',
                    'label' => 'Impressions',
                    'name' => 'impressions',
                    'type' => 'text',
                ],
            ],
        ],
        // end Social

        // Consultative
        [
            'key' => 'f_ser_tab_only_consul',
            'label' => 'Consultative',
            'name' => '',
            'type' => 'tab',
            'placement' => 'top',
        ],
        [
            'key' => 'f_ser_consul_only_title',
            'label' => 'Title',
            'name' => 'f_ser_consul_only_title',
            'type' => 'text',
        ],
        [
            'key' => 'f_ser_consul_only_repeater',
            'label' => 'Repeater',
            'name' => 'only_repeater',
            'type' => 'repeater',
            'instructions' => 'Add multiple entries with three text fields',
            'required' => 0,
            'collapsed' => '',
            'layout' => 'row',
            'min' => 1,
            'button_label' => 'Add new entry',
            'sub_fields' => [
                [
                    'key' => 'f_ser_consul_only__repeater_title',
                    'label' => 'Title',
                    'name' => 'title',
                    'type' => 'text',
                    'required' => 1,
                ],
                [
                    'key' => 'f_ser_consul_only_repeater_text',
                    'label' => 'Text',
                    'name' => 'f_ser_consul_only_repeater_editor',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'toolbar' => 'full',
                    'media_upload' => 0,
                    'default_value' => '',
                    'tabs' => 'all',
                    'max_width' => '',
                    'min_width' => '',
                    'max_height' => '',
                    'min_height' => '',
                ],
                [
                    'key' => 'f_ser_consul_only_repeater_img',
                    'label' => 'Image',
                    'name' => 'f_ser_consul_only_repeater_img',
                    'type' => 'image',
                    'required' => 0,
                ],
            ],
        ],
        // end Consultative

        // Connection
        [
            'key' => 'f_only_tab_connection',
            'label' => "Connection",
            'name' => '',
            'type' => 'tab',
            'placement' => 'top',
        ],
        [
            'key' => 'f_only_connection_title',
            'label' => 'Title',
            'name' => 'f_only_connection_title',
            'type' => 'text',
        ],
        [
            'key' => 'f_only_connection_repeater',
            'label' => 'Repeater',
            'name' => 'f_only_connection_repeat_fields',
            'type' => 'repeater',
            'instructions' => 'Add multiple entries with three text fields',
            'required' => 0,
            'collapsed' => '',
            'min' => 1,
            'layout' => 'row',
            'button_label' => 'Add new entry',
            'sub_fields' => [
                [
                    'key' => 'connection_repeater_image',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                ],

                [
                    'key' => 'connection_repeater_bot_f',
                    'label' => 'Label',
                    'name' => 'name_bot_f',
                    'type' => 'text',
                ],
                [
                    'key' => 'connection_repeater_bot_lin',
                    'label' => 'Note',
                    'name' => 'name_bot_lin',
                    'type' => 'text',
                ],

                [
                    'key' => 'connection_repeater_name',
                    'label' => 'Name',
                    'name' => 'name',
                    'type' => 'text',
                    'required' => 1,
                ],
                [
                    'key' => 'connection_repeater_description',
                    'label' => 'Description',
                    'name' => 'description',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'toolbar' => 'full',
                    'media_upload' => 0,
                    'default_value' => '',
                    'tabs' => 'all',
                    'max_width' => '',
                    'min_width' => '',
                    'max_height' => '',
                    'min_height' => '',
                ],
            ],
        ],
        // end Connection

        // bootom
        [
            'key' => 'f_only_bottom',
            'label' => "Bottom",
            'name' => '',
            'type' => 'tab',
            'placement' => 'top',
        ],
        [
            'key' => 'f_only_bottom_picture',
            'label' => 'Image ',
            'name' => 'f_only_bottom_picture',
            'type' => 'image',
        ],
        // end bottom
    ],
    'location' => [
        [
            [
                'param' => 'page',
                'operator' => '==',
                'value' => '19',
            ],
        ],
    ],
]);
